// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGw4T-WhitmwrnCJXxW1UIcE80oj3RlpM',
    appId: '1:137432503872:web:3c52d2d1ede78f78c5f1a5',
    messagingSenderId: '137432503872',
    projectId: 'your-ride-60e30',
    authDomain: 'your-ride-60e30.firebaseapp.com',
    storageBucket: 'your-ride-60e30.appspot.com',
    measurementId: 'G-YE06D6VDKZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBqnQOBbjYzJdRQpWfHorfRPQvUzcxGdKY',
    appId: '1:137432503872:android:b7dcce9216b948dfc5f1a5',
    messagingSenderId: '137432503872',
    projectId: 'your-ride-60e30',
    storageBucket: 'your-ride-60e30.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDC8nku5AnoFY3S_62QOVO4w1tGeSowFV0',
    appId: '1:137432503872:ios:597d4529e35b0688c5f1a5',
    messagingSenderId: '137432503872',
    projectId: 'your-ride-60e30',
    storageBucket: 'your-ride-60e30.appspot.com',
    iosBundleId: 'com.example.yourRide',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDC8nku5AnoFY3S_62QOVO4w1tGeSowFV0',
    appId: '1:137432503872:ios:70d1341942c5069fc5f1a5',
    messagingSenderId: '137432503872',
    projectId: 'your-ride-60e30',
    storageBucket: 'your-ride-60e30.appspot.com',
    iosBundleId: 'com.example.yourRide.RunnerTests',
  );
}
