// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCCKXy3kN7fd1162Z95-OXkFVYd9VEwDzA',
    appId: '1:991070457794:web:b2a884b283728f3481905b',
    messagingSenderId: '991070457794',
    projectId: 'your-ride-18dfe',
    authDomain: 'your-ride-18dfe.firebaseapp.com',
    storageBucket: 'your-ride-18dfe.appspot.com',
    measurementId: 'G-9731N7CBS1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANranB44CDw8hU-d31qcVGuzJucBRBqNc',
    appId: '1:991070457794:android:29d1a690a14a3f1081905b',
    messagingSenderId: '991070457794',
    projectId: 'your-ride-18dfe',
    storageBucket: 'your-ride-18dfe.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCqLwtRHrbxsO-DuJA500hpbW-yQVbS_vo',
    appId: '1:991070457794:ios:eb1540342c03d12781905b',
    messagingSenderId: '991070457794',
    projectId: 'your-ride-18dfe',
    storageBucket: 'your-ride-18dfe.appspot.com',
    iosBundleId: 'com.example.yourRide',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCqLwtRHrbxsO-DuJA500hpbW-yQVbS_vo',
    appId: '1:991070457794:ios:71041df1561a97cb81905b',
    messagingSenderId: '991070457794',
    projectId: 'your-ride-18dfe',
    storageBucket: 'your-ride-18dfe.appspot.com',
    iosBundleId: 'com.example.yourRide.RunnerTests',
  );
}
